name: my_ccml_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.0
  - matplotlib=3.8.0
  - numpy=1.26.1
  - opencv-python=4.8.1.78
  - pandas=2.1.1
  - Pillow=10.1.0
  - scipy=1.11.3
  - tqdm=4.66.1
  - wandb=0.15.12
  - numpy-stl=3.0.1