wandb_version: 1

architecture:
  desc: null
  value: DeepresUNet with layernorm
dataset:
  desc: null
  value: Strokes 1000
img_dimensions:
  desc: null
  value: 128
optimiser:
  desc: null
  value: Adam
lr:
  desc: null
  value: 0.003
betas:
  desc: null
  value:
  - 0.9
  - 0.999
weight_decay:
  desc: null
  value: 0
amsgrad:
  desc: null
  value: true
loss_function:
  desc: null
  value: BCE
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 42
transform:
  desc: null
  value: RandomRotateFlip
do_batchnorm:
  desc: null
  value: false
do_layernorm:
  desc: null
  value: true
clip_value:
  desc: null
  value: 1
time:
  desc: null
  value: 20230926-174514
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1695746718.260128
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.11.4
      5: 0.15.9
      8:
      - 3
      - 5
